kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: wordpress-you
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: production
  labels:
    app: wordpress-you
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-you
      track: stable
  template:
    metadata:
      labels:
        app: wordpress-you
        track: stable
    spec:
      containers:
      - name: wordpress
        image: 25092018/wordpress:@
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: wp_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: wp_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: wp_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: wp_pass                  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wordpress.rizdin.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: wordpress-service
          servicePort: 80
